require "rubocop/rake_task"
require "rake/testtask"

task default: %w[lint test]

RuboCop::RakeTask.new(:lint) do |task|
  task.patterns = ["lib/**/*.rb", "test/**/*.rb"]
  task.fail_on_error = false
end

task :run do
  ruby "lib/cool_program.rb"
end

Rake::TestTask.new do |task|
  task.libs << "test"
  task.test_files = FileList["test/*test.rb"]
  task.verbose = true
end
